# Jekyll Configuration for Kraven
title: "Kraven 🕷️"
tagline: "Hunt Abandoned GitHub Projects"
description: "Hunt abandoned GitHub repositories - Discover forgotten gems and resurrection candidates"
url: "https://twansolo.github.io"
baseurl: "/kraven"
logo: "/kraven.png"

# Site settings
author:
  name: "Kraven Project"
  email: "hello@kraven.dev"
  github: "twansolo"

# Build settings
markdown: kramdown
highlighter: rouge

# GitHub Pages compatible plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO and Social
twitter:
  username: twansolo
  card: summary_large_image

social:
  name: Kraven Project Hunter
  links:
    - https://github.com/twansolo/kraven
    - https://www.npmjs.com/package/kraven

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Hunt Projects"
    url: "/hunt/"
  - title: "Documentation"
    url: "/docs/"
  - title: "Examples"
    url: "/examples/"
  - title: "CLI Tool"
    url: "/cli/"
  - title: "GitHub"
    url: "https://github.com/twansolo/kraven"

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/
  examples:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"
  - scope:
      path: ""
      type: "examples"
    values:
      layout: "example"

# GitHub Pages settings
safe: true
incremental: false
lsi: false

# Kraven branding
kraven:
  tagline: "Hunt abandoned GitHub repositories"
  subtitle: "Discover forgotten gems and resurrection candidates"
  colors:
    primary: "#9d4edd"      # Spider purple
    secondary: "#7b2cbf"    # Darker purple
    accent: "#e0aaff"       # Light purple
    dark: "#3c096c"         # Deep purple
    background: "#0d0208"   # Almost black

# Social links
github_username: twansolo
repository: kraven

# Exclude files from processing
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - tsconfig.json
  - src/
  - dist/
  - .gitignore
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor/

# Include files
include:
  - _pages
